#!/usr/bin/env bash
# selftest.sh — does crn work end to end against the example bundle? PASS/FAIL + exit code. No network.
set -u
HERE=$(cd "$(dirname "$0")/.." && pwd); export PATH="$HERE/bin:$HOME/.local/bin:$PATH"
T=$(mktemp -d); trap 'rm -rf "$T"' EXIT; cp -r "$HERE/examples/bundle" "$T/b"; cp -r "$HERE/examples/files" "$T/files"; export CAIRN_BUNDLE="$T/b"; fail=0
t() { local name=$1; shift; if "$@" >/dev/null 2>&1; then echo "PASS $name"; else echo "FAIL $name"; fail=1; fi; }
t "iwe on PATH"                        command -v iwe
t "crn --version"                      bash -c "crn --version | grep -q '^crn 0'"
t "crn --help lists verbs"             bash -c "crn --help | grep -q sweep"
t "per-verb --help"                    bash -c "crn sweep --help | grep -q fixture"
t "pending --json"                     bash -c "crn pending --json | python3 -c 'import json,sys;assert json.load(sys.stdin)[0][\"key\"]'"
t "find --json"                        bash -c "crn find retry --json | python3 -c 'import json,sys;assert any(r[\"key\"]==\"work/product-431\" for r in json.load(sys.stdin))'"
t "trail --dry-run runs"               bash -c "crn trail --dry-run | grep -q '^trail:'"
t "init scaffolds a bundle"            bash -c "crn init $T/fresh | grep -q 'bundle ready' && test -f $T/fresh/.hooks/session-end.sh && test -f $T/fresh/.iwe/schemas/work.yaml"
t "doctor runs"                        bash -c "CAIRN_BUNDLE=$T/b crn doctor | grep -q '^RESULT'"
t "bundle validates"                   bash -c "crn validate | grep -qiv 'error\|violation' "
t "tidy: clean bundle has nothing to weed" bash -c "crn tidy | grep -q 'nothing to weed'"
t "tidy finds a dangling Context line"   bash -c "sed -i '/^## Context/a - a finding → ../../files/missing.md' $T/b/work/product-431.md && crn tidy | grep -q 'dangling' && crn tidy --json | python3 -c 'import json,sys;d=json.load(sys.stdin);assert d[\"total\"]>0 and \"dangling\" in d[\"findings\"]'"
t "find by system alias"               bash -c "crn find checkout | grep -q 'systems/order-api'"
t "find by state words"                bash -c "crn find pricing | grep -q 'product-419'"
t "open by number"                     bash -c "crn open 431 | grep -q '^## Now'"
t "open by slug prefix"                bash -c "crn open platform-4 2>&1 | grep -q ambiguous"
t "open shows backlinks"               bash -c "crn open systems/order-api | grep -q 'linked from'"
t "pending excludes done"              bash -c "crn pending | grep -q product-431 && ! crn pending | grep -q platform-422"
t "log appends under ## Log"           bash -c "crn log 419 'selftest line' && grep -q 'selftest line' $T/b/work/product-419.md && grep -q 'updated: $(date +%F)' $T/b/work/product-419.md"
t "decide appends under ## Decisions"  bash -c "crn decide 431 'selftest decision' && awk '/^## Decisions/,/^## Context/' $T/b/work/product-431.md | grep -q 'selftest decision'"
t "state refuses more than 200 chars"   bash -c "! crn state 362 \"$(printf 'x%.0s' {1..201})\" 2>/dev/null && crn validate | grep -q '^valid'"
t "state sets one sentence"            bash -c "crn state 362 'selftest state' && grep -q 'state: selftest state' $T/b/work/platform-362.md"
t "sweep updates gh fields (fixture)"  bash -c "crn sweep --fixture $HERE/examples/github-fixture.json | grep -q 'updated work/product-431'"
t "sweep lists issues without a node"  bash -c "crn sweep --fixture $HERE/examples/github-fixture.json | grep -q 'new .*compliance#512'"
t "sweep lists review requests and my PRs" bash -c "crn sweep --fixture $HERE/examples/github-fixture.json | grep -q 'review requested from you (1)' && crn sweep --fixture $HERE/examples/github-fixture.json | grep -q 'your open PRs (1)'"
t "sweep --create makes a valid node"  bash -c "crn sweep --fixture $HERE/examples/github-fixture.json --create >/dev/null && test -f $T/b/work/compliance-512.md && crn validate | grep -qiv 'error\|violation'"
t "priority legend prints"             bash -c "crn priority | grep -q 'P1  Outage'"
t "priority set by word"               bash -c "crn priority 431 security && grep -q 'priority: 2' $T/b/work/product-431.md && grep -q 'priority_by: human' $T/b/work/product-431.md"
t "priority bad word exits 1"          bash -c "! crn priority 431 urgent"
t "pending sorts P1 first"             bash -c "crn priority 419 1 >/dev/null && crn pending | head -1 | grep -q 'P1 .*product-419'"
t "sweep proposes, never overwrites"   bash -c "crn sweep --fixture $HERE/examples/github-fixture.json --create >/dev/null && grep -q 'priority: 3' $T/b/work/compliance-512.md || grep -q 'priority_by: sweep' $T/b/work/compliance-512.md; grep -q 'priority: 2' $T/b/work/product-431.md"
t "Context section opens with the node" bash -c "crn open 431 | grep -q '^## Context' && crn open 431 | grep -q 'reproduction log.*→ ../../files/'"
t "lazy files stay outside the bundle" bash -c "! crn find 'pricing notes' | grep -q 'files/\|artifacts/'"
t "runbook line lives on the system"   bash -c "crn open systems/cluster | grep -q '^- roll the cluster.*→'"
t "sweep refreshes the graph"         bash -c "rm -f $T/b/.cairn/graph.html; crn sweep --fixture $HERE/examples/github-fixture.json >/dev/null && test -f $T/b/.cairn/graph.html"
t "graph html embeds data"            bash -c "crn graph >/dev/null && grep -q '\"nodes\"' $T/b/.cairn/graph.html && ! grep -q 'GRAPH_JSON\*/null' $T/b/.cairn/graph.html"
t "graph json has edges"              bash -c "crn graph --format json --include-done >/dev/null && python3 -c 'import json;g=json.load(open(\"$T/b/.cairn/graph.json\"));assert g[\"counts\"][\"edges\"]>3 and any(e[\"rel\"]==\"blocked_by\" for e in g[\"edges\"])'"
t "roll parks old Log lines outside"  bash -c "for i in 1 2 3 4 5 6 7; do crn log 419 \"roll line \$i\" >/dev/null; done; crn roll 419 --keep 2 | grep -q 'rolled' && test -f $T/files/product-419/log.md && grep -q 'roll line 1' $T/files/product-419/log.md && ! grep -q 'roll line 1' $T/b/work/product-419.md && grep -q '^- earlier Log.*→ ../../files/product-419/log.md' $T/b/work/product-419.md && crn validate | grep -q '^valid'"
t "roll twice appends, one Context line" bash -c "crn log 419 'roll line 8' >/dev/null && crn roll 419 --keep 2 >/dev/null && grep -c 'roll line' $T/files/product-419/log.md | grep -q '^6' && grep -c '^- earlier Log' $T/b/work/product-419.md | grep -q '^1'"
t "stage parked rolls the Log to one line" bash -c "crn stage 431 parked | grep -q 'stage parked' && test \$(awk '/^## Log/{f=1;next} /^## /{f=0} f && /^- /' $T/b/work/product-431.md | wc -l) -eq 1 && test -f $T/files/product-431/log.md"
t "trail: a line already on the node is not appended twice" bash -c "crn log 431 'dup guard' >/dev/null && n=\$(grep -c 'dup guard' $T/b/work/product-431.md) && crn trail --dry-run >/dev/null && test \$n -eq 1"
t "trail: lock file exists after a run"  bash -c "crn trail >/dev/null; test -f $T/b/.cairn/trail.lock"
t "graph has you as a node"          bash -c "crn graph --format json >/dev/null && python3 -c 'import json;g=json.load(open(\"$T/b/.cairn/graph.json\"));me=g[\"me\"];assert any(n[\"id\"]==me and n.get(\"me\") for n in g[\"nodes\"]);assert any(e[\"t\"]==me and e[\"rel\"] in (\"review\",\"yours\") for e in g[\"edges\"])'"
t "graph gexf is xml"                 bash -c "crn graph --format gexf >/dev/null && head -1 $T/b/.cairn/graph.gexf | grep -q '<?xml'"
t "unknown node exits 1"               bash -c "! crn open nothing-here-xyz"
t "still valid after writes"           bash -c "crn validate | grep -qiv 'error\|violation'"
[ $fail -eq 0 ] && echo "RESULT PASS" || echo "RESULT FAIL"; exit $fail
